### ISSUE TITLE
why train_y converted by np.eye for GPU code?

### ISSUE THREAD

**Issue by arisliang** [dennybritz/nn-theano#1]
Referring to "Speeding up your Neural Network with Theano and the GPU", why for GPU code, train_y is converted by np.eye?
For CPU code, it's not.

**Comment by dennybritz** [comment]
Looking at the documentation it seems like both work to calculate the cross-entropy: http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html#tensor.nnet.categorical_crossentropy

Also, using `np.eye` is a very inefficient way to make a one-hot vector since it builds the full identity matrix first. Really shouldn't use that.

**Comment by arisliang** [comment]
Actually, I tried if without np.eye, the example won't run for GPU, but it runs for CPU.

**Comment by dennybritz** [comment]
It could be that the operation is not implemented on the GPU in Theano (CPU and GPU have different implementations and not everything is supported) and that's why you need to use one-hot vectors. You'd be able to see that from the error message though. Sorry, it has been a while since I wrote this code and I don't remember why exactIy I changed it to one-hot vectors.
